import os
import json
from datetime import datetime
from pathlib import Path

# 현재 스크립트 위치(scripts/)의 상위 폴더(루트)를 기준으로 경로 설정
CURRENT_DIR = Path(__file__).resolve().parent
ROOT_DIR = CURRENT_DIR.parent

DATA_DIR = ROOT_DIR / 'by_created'
COUNTS_FILE = ROOT_DIR / 'RBLOGGERS_COUNTS.json'
STATS_FILE = ROOT_DIR / 'RBLOGGERS_REPO_STATS.md'
ACTION_RESULT_FILE = ROOT_DIR / '.action_result.json'

def scan_repository():
    """
    by_created 디렉토리 전체를 스캔하여 연/월별 통계를 생성합니다.
    (기존 값을 믿지 않고 매번 새로 셉니다 -> 오류 가능성 0%)
    """
    stats = {}
    total_files = 0
    total_bytes = 0
    
    if not DATA_DIR.exists():
        print(f"Warning: {DATA_DIR} does not exist.")
        return stats, 0, 0

    # 연도(YYYY) 디렉토리 순회
    for year_path in sorted(DATA_DIR.iterdir()):
        if not year_path.is_dir() or not year_path.name.isdigit():
            continue
        
        year = year_path.name
        
        # 월(MM) 디렉토리 순회
        for month_path in sorted(year_path.iterdir()):
            if not month_path.is_dir() or not month_path.name.isdigit():
                continue
                
            month = month_path.name
            key = f"{year}-{month}"
            
            # 해당 월의 .json 파일 전수 조사
            files = list(month_path.glob("*.json"))
            count = len(files)
            size = sum(f.stat().st_size for f in files)
            
            if count > 0:
                stats[key] = {"files": count, "bytes": size}
                total_files += count
                total_bytes += size

    return stats, total_files, total_bytes

def load_last_run_info():
    """크롤러(crawl_rbloggers.py)가 생성한 임시 결과 파일에서 최근 실행 정보를 읽어옵니다."""
    info = {"status": "Unknown", "new_count": 0}
    if ACTION_RESULT_FILE.exists():
        try:
            with open(ACTION_RESULT_FILE, 'r', encoding='utf-8') as f:
                data = json.load(f)
                info["status"] = data.get("status", "Unknown")
                # 크롤러가 기록한 new_count를 가져오거나, 없으면 0
                info["new_count"] = data.get("new_count", 0) 
        except Exception as e:
            print(f"Error reading action result: {e}")
    return info

def update_stats_files(monthly_stats, total_files, total_bytes, last_run_info):
    """JSON 및 MD 파일을 갱신합니다."""
    
    # 1. RBLOGGERS_COUNTS.json 업데이트
    sorted_keys = sorted(monthly_stats.keys(), reverse=True) # 최신 월이 위로
    sorted_stats = {k: monthly_stats[k] for k in sorted_keys}
    
    output_json = {
        "meta": {
            "total_posts": total_files,
            "total_bytes": total_bytes,
            "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S KST"),
            "last_crawl_status": last_run_info["status"],
            "last_crawl_new_files": last_run_info["new_count"]
        },
        "monthly_counts": sorted_stats
    }
    
    with open(COUNTS_FILE, 'w', encoding='utf-8') as f:
        json.dump(output_json, f, indent=2)
    print(f"✅ Updated {COUNTS_FILE}")

    # 2. RBLOGGERS_REPO_STATS.md 업데이트
    mb_size = total_bytes / (1024 * 1024)
    
    md_content = [
        "# R-bloggers Data Repository Statistics",
        "",
        "## 📊 Repository Status",
        f"- **Total Archived Posts:** {total_files:,}",
        f"- **Total Data Size:** {mb_size:.2f} MB",
        f"- **Last Updated:** {output_json['meta']['last_updated']}",
        "",
        "## 🔄 Last Crawl Info",
        f"- **Status:** {last_run_info['status']}",
        f"- **New Posts Added:** {last_run_info['new_count']}",
        "",
        "## 📅 Monthly Archive History",
        "| Month | Posts | Size (KB) |",
        "| :--- | :---: | :---: |"
    ]
    
    for key in sorted_keys:
        data = monthly_stats[key]
        kb_size = data['bytes'] / 1024
        md_content.append(f"| **{key}** | {data['files']:,} | {kb_size:,.1f} KB |")
    
    md_content.append("")
    md_content.append("---")
    md_content.append(f"\n*This report is automatically generated by Statground Platform.*")

    with open(STATS_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(md_content))
    print(f"✅ Updated {STATS_FILE}")

if __name__ == "__main__":
    print("--- Starting Repository Stats Update (Full Scan) ---")
    monthly_stats, total_files, total_bytes = scan_repository()
    last_run = load_last_run_info()
    update_stats_files(monthly_stats, total_files, total_bytes, last_run)
    print("--- Update Finished ---")